### ISSUE TITLE
Infinite "Processing" State for Invalid URLs in CodeDrop

### ISSUE THREAD

**Issue by onkar69483** [onkar69483/CodeDrop#12]
When a user navigates to a URL that does not correspond to a valid paste ID on the CodeDrop website, the page gets stuck in an infinite "Processing" state. There is no error message displayed to the user, which leads to confusion and a poor user experience.

**Steps to Reproduce:**

1. Visit the CodeDrop website.
2. Enter an invalid or non-existent URL, such as `https://codedrop.vercel.app/something`.
3. Observe that the page continuously shows the "Processing..." state without any error message or indication of the issue.

**Expected Behavior:**

- An appropriate error message should be displayed to inform the user that the paste ID is invalid or does not exist.
- The "Processing" state should not persist indefinitely.

**Actual Behavior:**

- The "Processing" state remains active indefinitely for invalid URLs.
- There is no error message or indication that the URL is invalid.

**Relevant Code:**

The issue might be related to error handling in the `/src/routes/[id]/+page.svelte` file. Review the fetch request and error handling logic to ensure that invalid responses are appropriately handled and displayed.

**Proposed Solution:**

- Implement error handling for invalid paste IDs.
- Display a user-friendly error message indicating the issue with the URL.
- Ensure that the "Processing" state is exited once an error is encountered.

**Screenshots:**

![processing](https://github.com/user-attachments/assets/80fa377c-8b70-4ac5-9331-6e6d53f3b437)

**Additional Context:**

This issue affects user experience and may lead to confusion when navigating to invalid URLs. Proper error handling and messaging will improve usability.

**Comment by Aryanfour5** [comment]
me

**Comment by Aryanfour5** [comment]
I can take the issue

**Comment by onkar69483** [comment]
Assigned @Aryanfour5
